gramlite/urls.py
from django.conf.urls import url
from . import views

app_name = 'gramlite'
urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^check_user', views.Check_User.as_view(), name='check-user'),
    url(r'^gallery/(?P<username>\w+)/(?P<templateid>\w+)/$', views.Styles.as_view(), name='styles'),
]

instagram/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gramlite/', include('gramlite.urls')),
]

gramlite/models.py
from __future__ import unicode_literals
from django.db import models

class User(models.Model):
    name = models.CharField(max_length=300)
    user_id = models.IntegerField(default=0)

    # def get_id_by_username(self,username):
    #     user_obj = self.objects.get(name=username)
    #     return user_obj.id

class Image(models.Model):
    image_link = models.CharField(max_length=3000)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def get_images_by_user(self, current_user):
        return current_user.image_set.all()

    def __str__(self):
        return str(User.name)

gramlite/forms.py
from django import forms
from django.forms import ModelForm
from .models import User

gramlite/views.py
from django.shortcuts import render, redirect
from .models import User, Image
import requests
from django.views.generic import View


class Check_User(View):

    def check_user(self, request):
        username = request.POST['username']
        if username:
            user_id = self.get_user_id(username, request)
            if user_id:
                user = self.user_already_exists(username, user_id)
                images = self.get_images(user)
                user_info = {
                    'images': images,
                    'username': username

                }

                return redirect('gallery/'+username+'/1')
                # return render(request, 'gramlite/template1.html', user_info)
                # return HttpResponseRedirect("https://api.instagram.com/v1/users/%s/media/recent/?access_token=1497402817.1fb234f.1b8969bb3b304945a6782ae574069017" % user_id)
        return self.no_user_case(request)



    def get_user_id(self, username, request):
        response = requests.get('https://api.instagram.com/v1/users/search?access_token=1497402817.1fb234f.1b8969bb3b304945a6782ae574069017&q=' + username)
        res = response.json()['data']
        if len(res) > 0:
            for user in res:
                if username == user['username']:
                    user_id = user['id']
                    print user_id
                    return user_id
        else:
            return 0

    def user_already_exists(self, username, user_id):
        user= User.objects.filter(name=username)
        if not user:
            user = User(name=username, user_id=user_id)
            user.save()
        else:
            user = user[0]
        return user

    def get_images(self, user):
        image_link = requests.get("https://api.instagram.com/v1/users/%s/media/recent/?access_token=1497402817.1fb234f.1b8969bb3b304945a6782ae574069017" % user.user_id)
        image_data = image_link.json()
        image_list = []
        for i in image_data['data']:
            image_data = i['images']
            image_o = image_data['standard_resolution']
            new_img = image_o['url']
            image_search = Image.objects.filter(image_link=new_img)
            if image_search:
                image_list.append(image_search)
            else:
                img = Image(image_link=new_img, user_id=user)
                img.save()
                image_list.append(img)
        return image_list

    def no_user_case(self, request):
        context = {'status': 'not found'}
        return render(request, 'gramlite/home.html', context)

    def post(self, request):
        return self.check_user(request)



def home(request):
    return render(request, 'gramlite/home.html')


class Styles(View):
    def get(self, request, username, templateid):
        user = User.objects.get(name=username)
        username = user.name
        images = user.image_set.all()
        user_info = {
                    'images': images,
                    'username': username
                }
        return render(request, 'gramlite/'+'template'+templateid+'.html', user_info)

gramlite/templates/gramlite/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>GramLite</title>

    <!-- Bootstrap core CSS -->
      {% load staticfiles %}
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'css/base.css' %}" rel="stylesheet">
    {% block cssfile %}{% endblock %}

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/gramlite/static/css/navbar-fixed-top.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="row">
                <div class="log">
{#                    <div class="col-sm-8 col-sm-offset-8">#}
                        <a href={% url 'gramlite:home' %}><img class="logo" src={% static 'images/gramlite.png' %}></a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    {% block images %}
    {% endblock %}

    {% block form %}
    {% endblock %}



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/gramlite/js/vendor/jquery.min.js"></script>
    <script src="/gramlite/static/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

gramlite/templates/gramlite/base_styles.html
{% extends 'gramlite/base.html' %}

gramlite/templates/gramlite/home.html
{% extends 'gramlite/base.html' %}
{% load staticfiles %}
{% block cssfile %}<link rel="stylesheet" href={% static 'css/home.css' %}>{% endblock %}

{% block form %}
    <div class="container search">
        <div class="row">
            <div class="bar">
            <div class="form-cont">
                        <form name="searchForm" class="form" action="/gramlite/check_user" method="post">
                            {% csrf_token %}
                            <input name="username" type="text" class="form-control" placeholder="Your instagram name...">
                            <span class="input-group-btn">
                                <button class="load-gallery btn btn-default" type="submit" value="Submit">Load My Gallery!</button>
                            </span>
                        </form>
                {% if status == 'not found'%}
                    <p class="error-message">Oops! Either this account is private or doesn't exist!</p>
                {% endif %}
            </div>
            </div><!-- /.col-sm-8 -->
        </div><!-- /.row -->
    </div> <!-- /container -->

{% endblock %}

gramlite/templates/gramlite/template1.html
{% extends 'gramlite/base.html' %}
{% load staticfiles %}
{% block cssfile %}

    <link rel="stylesheet" href={% static 'css/picture.css' %}>

{% endblock %}

{#Tempalte id in range; send those back to view.#}
{#Load HTML files with template names instead#}
{% block images %}
    <div class="holder container">
    <div class="filter-holder">
        <a href={% url 'gramlite:styles' username=username templateid="4"%} ><div class="filter grayscale">Grayscale</div></a>
        <a href={% url 'gramlite:styles' username=username templateid="5"%} ><div class="filter blur">Blur</div></a>
        <a href={% url 'gramlite:styles' username=username templateid="3"%} ><div class="filter invert">Invert</div></a>
        <a href={% url 'gramlite:styles' username=username templateid="2"%} ><div class="filter saturate">Saturate</div></a>
        <a href={% url 'gramlite:styles' username=username templateid="1"%} ><div class="filter">Regular</div></a>

    </div>
    <h1 class="header">Welcome {{ username }}</h1>
        <div class="row">
            <div class="col-sm-12">
            {% for image in images %}
                <div class="col-sm-3">
                    <div class="image-holder">
                        <img class="image" src={{ image.image_link }}>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}

gramlite/templates/gramlite/template2.html
{% extends 'gramlite/base.html' %}
{% load staticfiles %}
{% block cssfile %}<link rel="stylesheet" href={% static 'css/saturate.css' %}>{% endblock %}


{% block images %}
    <div class="holder container">
    <div class="filter-holder">
          <div class="filter-holder">
              <a href={% url 'gramlite:styles' username=username templateid="4"%} ><div class="filter grayscale">Grayscale</div></a>
              <a href={% url 'gramlite:styles' username=username templateid="5"%} ><div class="filter blur">Blur</div></a>
              <a href={% url 'gramlite:styles' username=username templateid="3"%} ><div class="filter invert">Invert</div></a>
              <a href={% url 'gramlite:styles' username=username templateid="2"%} ><div class="filter saturate">Saturate</div></a>
              <a href={% url 'gramlite:styles' username=username templateid="1"%} ><div class="filter">Regular</div></a>
    </div>
    </div>
    <h1 class="header">Welcome {{ username }}</h1>
        <div class="row">
            <div class="col-sm-12">
            {% for image in images %}
                <div class="col-sm-3">
                    <div class="image-holder">
                        <img class="image" src={{ image.image_link }}>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}

gramlite/templates/gramlite/template3.html
{% extends 'gramlite/base.html' %}
{% load staticfiles %}
{% block cssfile %}<link rel="stylesheet" href={% static 'css/invert.css' %}>{% endblock %}


{% block images %}
    <div class="holder container">
        <div class="filter-holder">
            <div class="filter-holder">
                <a href={% url 'gramlite:styles' username=username templateid="4"%} ><div class="filter grayscale">Grayscale</div></a>
                <a href={% url 'gramlite:styles' username=username templateid="5"%} ><div class="filter blur">Blur</div></a>
                <a href={% url 'gramlite:styles' username=username templateid="3"%} ><div class="filter invert">Invert</div></a>
                <a href={% url 'gramlite:styles' username=username templateid="2"%} ><div class="filter saturate">Saturate</div></a>
                <a href={% url 'gramlite:styles' username=username templateid="1"%} ><div class="filter">Regular</div></a>
            </div>
        </div>
        <h1 class="header">Welcome {{ username }}</h1>
        <div class="row">
            <div class="col-sm-12">
                {% for image in images %}
                    <div class="col-sm-3">
                        <div class="image-holder">
                            <img class="image" src={{ image.image_link }}>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}

gramlite/templates/gramlite/template4.html
{% extends 'gramlite/base.html' %}
{% load staticfiles %}
{% block cssfile %}<link rel="stylesheet" href={% static 'css/grayscale.css' %}>{% endblock %}


{% block images %}
    <div class="holder container">
        <div class="filter-holder">
            <div class="filter-holder">
                <a href={% url 'gramlite:styles' username=username templateid="4"%} ><div class="filter grayscale">Grayscale</div></a>
                <a href={% url 'gramlite:styles' username=username templateid="5"%} ><div class="filter blur">Blur</div></a>
                <a href={% url 'gramlite:styles' username=username templateid="3"%} ><div class="filter invert">Invert</div></a>
                <a href={% url 'gramlite:styles' username=username templateid="2"%} ><div class="filter saturate">Saturate</div></a>
                <a href={% url 'gramlite:styles' username=username templateid="1"%} ><div class="filter">Regular</div></a>
            </div>
        </div>
        <h1 class="header">Welcome {{ username }}</h1>
        <div class="row">
            <div class="col-sm-12">
                {% for image in images %}
                    <div class="col-sm-3">
                        <div class="image-holder">
                            <img class="image" src={{ image.image_link }}>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}

gramlite/templates/gramlite/template5.html
{% extends 'gramlite/base.html' %}
{% load staticfiles %}
{% block cssfile %}<link rel="stylesheet" href={% static 'css/blur.css' %}>{% endblock %}


{% block images %}
    <div class="holder container">
        <div class="filter-holder">
            <a href={% url 'gramlite:styles' username=username templateid="4"%} ><div class="filter grayscale">Grayscale</div></a>
            <a href={% url 'gramlite:styles' username=username templateid="5"%} ><div class="filter blur">Blur</div></a>
            <a href={% url 'gramlite:styles' username=username templateid="3"%} ><div class="filter invert">Invert</div></a>
            <a href={% url 'gramlite:styles' username=username templateid="2"%} ><div class="filter saturate">Saturate</div></a>
            <a href={% url 'gramlite:styles' username=username templateid="1"%} ><div class="filter">Regular</div></a>
        </div>
        <h1 class="header">Welcome {{ username }}</h1>
        <div class="row">
            <div class="col-sm-12">
                {% for image in images %}
                    <div class="col-sm-3">
                        <div class="image-holder">
                            <img class="image" src={{ image.image_link }}>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>
{% endblock %}